/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import java.util.ArrayList;
import java.util.stream.Collectors;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import poo.clases.Direccion;
import poo.clases.Inmueble;
import poo.clases.JavaBNB;

/**
 *
 * @author Marcos Barroso
 */
public class PanelInmuebles extends javax.swing.JPanel {

    private final JFrame parent;
    private final ArrayList<Inmueble> inmuebles = JavaBNB.getInmuebles();

    /**
     * Creates new form PanelInmuebles
     *
     * @param parent
     */
    public PanelInmuebles(JFrame parent) {
        initComponents();
        this.parent = parent;
        mostrarInmuebles(inmuebles);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setLayout(new java.awt.GridLayout(0, 4, 5, 5));
        jScrollPane1.setViewportView(jPanel);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        getInmuebles();
        jComboBox1.setBackground(new java.awt.Color(255, 153, 51));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mostrar por ciudad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(739, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        try {
            String selection = (String) jComboBox1.getSelectedItem();
            if (selection.equals("Todos")) {
                mostrarInmuebles(inmuebles);
            } else {
                mostrarInmuebles(selection);
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No hay reservas", "Mensaje", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    private void mostrarInmuebles(ArrayList<Inmueble> inmuebles) {
        try {
            jPanel.removeAll();
            if (inmuebles.isEmpty()) {
                JLabel jt = new javax.swing.JLabel();
                jt.setText("No se encuentran inmuebles para esa dirección");
                jt.setFont(new java.awt.Font("Segoe UI", 0, 16));
                jPanel.add(jt);
            } else {
                for (Inmueble i : inmuebles) {
                    PanelInmVistaPrevia p = new PanelInmVistaPrevia(i, parent, false);
                    p.setSize(206, 303);
                    jPanel.add(p);
                }
            }
            jPanel.revalidate();
            jPanel.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Inmuebles", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarInmuebles(String ciudad) {
        try {
            ArrayList<Inmueble> inmueblesCiudad = JavaBNB.getInmueblesCiudad(ciudad);
            jPanel.removeAll();
            if (inmueblesCiudad.isEmpty()) {
                JLabel jt = new javax.swing.JLabel();
                jt.setText("No se encuentran inmuebles para esa dirección");
                jt.setFont(new java.awt.Font("Segoe UI", 0, 16));
                jPanel.add(jt);
            } else {
                for (Inmueble i : inmueblesCiudad) {
                    PanelInmVistaPrevia p = new PanelInmVistaPrevia(i,parent,false);
                    p.setSize(206, 266);
                    jPanel.add(p);
                }
            }
            jPanel.revalidate();
            jPanel.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Inmuebles", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void getInmuebles() {
        try {
            ArrayList<String> ciudades = (ArrayList) JavaBNB.getInmuebles().stream().map(Inmueble::getDireccion).map(Direccion::getLocalidad).distinct().collect(Collectors.toList());
            ciudades.add(0, "Todos");
            jComboBox1 = new JComboBox(ciudades.toArray());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
