/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import poo.clases.FechaException;
import poo.clases.Inmueble;
import poo.clases.JavaBNB;
import poo.clases.Particular;

/**
 *
 * @author Marcos Barroso
 */
public class PanelBuscarInm extends javax.swing.JPanel {
    private final JFrame parent;
    private final Particular particular;
    /**
     * Creates new form PanelBuscarInm
     * @param parent
     * @param p particular
     */
    public PanelBuscarInm(JFrame parent,Particular p) {
        initComponents();
        jComboBoxTipo.setVisible(false);
        this.parent=parent;
        this.particular=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLocalidad = new javax.swing.JTextField();
        jComboBoxModoOrdenacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFechaIn = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFechaOut = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(1060, 550));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1058, 32767));
        jPanel1.setLayout(new java.awt.GridLayout(0, 4, 5, 5));
        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Destino:");

        jTextFieldLocalidad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jComboBoxModoOrdenacion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jComboBoxModoOrdenacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relevancia", "Tipo :", "Precio" }));
        jComboBoxModoOrdenacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModoOrdenacionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Ordenar por:");

        jComboBoxTipo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa" }));
        jComboBoxTipo.setSelectedIndex(-1);

        jButtonAceptar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButtonAceptar.setText("Buscar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Fecha de entrada:");

        try {
            jFormattedTextFechaIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFechaIn.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Fecha de salida:");

        try {
            jFormattedTextFechaOut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFechaOut.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxModoOrdenacion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFormattedTextFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jFormattedTextFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModoOrdenacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFechaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private String modo="Relevancia";
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        try {
            String localidad = jTextFieldLocalidad.getText();
            String fechaIn = jFormattedTextFechaIn.getText();
            String fechaOut = jFormattedTextFechaOut.getText();
            if (localidad.equals("")||fechaIn.equals("  /  /    ")||fechaOut.equals("  /  /    ")) throw new NullPointerException();
            if (fechaIn.equals(fechaOut)) throw new FechaException("La fecha de entrada y de salida deben ser distintas");
            LocalDate fechaEntrada = JavaBNB.setFechaFutura(fechaIn);
            LocalDate fechaSalida = JavaBNB.setFechaFutura(fechaOut);
            if(fechaEntrada.isAfter(fechaSalida)) throw new FechaException("La fecha de salida debe ser posterior a la de entrada");
            ArrayList<Inmueble> inmuebles = new ArrayList<>();
            switch (modo) {
                case "Relevancia" -> {
                    inmuebles = particular.buscarInmuebleOrdenRelevancia(localidad);
                    break;
                }
                case "Precio" -> {
                    inmuebles = particular.buscarInmuebleOrdenPrecio(localidad);
                    break;
                }
                case "Tipo :" -> {
                    String tipo = (String) jComboBoxTipo.getSelectedItem();
                    inmuebles = particular.buscarInmuebleOrdenTipo(localidad, tipo);
                    break;
                }
            }
            mostrarInmuebles(inmuebles,fechaEntrada,fechaSalida);
            //jComboBoxModoOrdenacionActionPerformed(evt);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Hay elementos vacíos", "Búsqueda de inmueble", JOptionPane.ERROR_MESSAGE);
        }catch (FechaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage()+"\nModifique las fechas", "Búsqueda de inmueble", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Búsqueda de inmueble", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jComboBoxModoOrdenacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModoOrdenacionActionPerformed
        // TODO add your handling code here:
        modo = (String) jComboBoxModoOrdenacion.getSelectedItem();
        if (modo.equals("Relevancia") || modo.equals("Precio")) jComboBoxTipo.setVisible(false);
        else jComboBoxTipo.setVisible(true);
    }//GEN-LAST:event_jComboBoxModoOrdenacionActionPerformed

    private void mostrarInmuebles(ArrayList<Inmueble> inmuebles,LocalDate fechaEntrada,LocalDate fechaSalida) {
        try {
            jPanel1.removeAll();
            if (inmuebles.isEmpty()) {
                JLabel jt = new javax.swing.JLabel();
                jt.setText("No se encuentran inmuebles para esa dirección");
                jt.setFont(new java.awt.Font("Segoe UI", 0, 16));
                jPanel1.add(jt);
            } else {
                for (Inmueble i : inmuebles) {
                    PanelInmVistaPrevia p = new PanelInmVistaPrevia(i,parent, fechaEntrada, fechaSalida,true,particular);
                    p.setSize(206, 303);
                    jPanel1.add(p);
                }
            }
            jPanel1.revalidate();
            jPanel1.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Búsqueda de inmueble", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBoxModoOrdenacion;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFechaIn;
    private javax.swing.JFormattedTextField jFormattedTextFechaOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldLocalidad;
    // End of variables declaration//GEN-END:variables
}
