/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import java.awt.BorderLayout;
import java.text.DecimalFormat;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import poo.clases.Anfitrion;
import poo.clases.Inmueble;
import poo.clases.Particular;

/**
 *
 * @author Marcos Barroso
 */
public class PanelInmVistaPrevia extends javax.swing.JPanel {

    JFrame parent;
    private Particular particular;
    private final Inmueble inm;
    private LocalDate fechaSalida, fechaEntrada;
    private boolean reservar, editar=false;
    private JPanel panelAnterior;
    private Anfitrion anfitrion;

    /**
     * Creates new form PanelInmVistaPrevia desde ventana particular
     *
     * @param i
     * @param parent
     * @param fechaEntrada
     * @param fechaSalida
     * @param reservar
     * @param p
     */
    public PanelInmVistaPrevia(Inmueble i, JFrame parent, LocalDate fechaEntrada, LocalDate fechaSalida, boolean reservar, Particular p) {
        initComponents();
        inm = i;
        cargarDatos();
        this.parent = parent;
        this.fechaEntrada = fechaEntrada;
        this.fechaSalida = fechaSalida;
        this.reservar = reservar;
        this.particular = p;
    }

    /**
     * Creates new form PanelInmVistaPrevia desde ventana administrador
     *
     * @param i
     * @param parent
     * @param reservar
     */
    public PanelInmVistaPrevia(Inmueble i, JFrame parent, boolean reservar) {
        initComponents();
        inm = i;
        cargarDatos();
        this.parent = parent;
        this.reservar = reservar;
    }
    
    /**
     * Creates new form PanelInmVistaPrevia desde ventana anfitrion
     * @param i
     * @param parent
     * @param reservar
     * @param editar
     * @param panel
     * @param a 
     */
    public PanelInmVistaPrevia(Inmueble i, JFrame parent, boolean reservar, boolean editar, JPanel panel,Anfitrion a) {
        initComponents();
        inm = i;
        cargarDatos();
        this.parent = parent;
        this.reservar = reservar;
        this.editar = editar;
        this.panelAnterior = panel;
        this.anfitrion=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFoto = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelLocalidad = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelCalificacion = new javax.swing.JLabel();
        jButtonDetalleVer = new javax.swing.JButton();
        jLabelSuperAnfitrion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 242, 222));
        setMaximumSize(new java.awt.Dimension(206, 303));
        setName(""); // NOI18N

        jLabelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setText("Titulo");

        jLabelLocalidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLocalidad.setText("Localidad");

        jLabelPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPrecio.setText("Precio");

        jLabelCalificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCalificacion.setText("Calificacion");

        jButtonDetalleVer.setBackground(new java.awt.Color(255, 153, 51));
        jButtonDetalleVer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonDetalleVer.setText("Ver detalles");
        jButtonDetalleVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalleVerActionPerformed(evt);
            }
        });

        jLabelSuperAnfitrion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSuperAnfitrion.setForeground(new java.awt.Color(255, 51, 51));
        jLabelSuperAnfitrion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSuperAnfitrion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDetalleVer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLocalidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCalificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDetalleVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSuperAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetalleVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalleVerActionPerformed
        try {
            AuxDetallesInmueble v = null;
            if (reservar) {
                v = new AuxDetallesInmueble(parent, true, inm, particular, fechaEntrada, fechaSalida, reservar);
                v.setVisible(true);
            } else if (!reservar && !editar) {
                v = new AuxDetallesInmueble(parent, true, inm, particular, reservar);
                v.setVisible(true);
            } else if (!reservar && editar) {
                PanelEditarInmueble p = new PanelEditarInmueble(inm, panelAnterior,parent,anfitrion);
                showPanel(p);
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Búsqueda de inmueble", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Búsqueda de inmueble", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDetalleVerActionPerformed

    private void cargarDatos() {
        try {
            ImageIcon img = new ImageIcon("./imagenes/" + inm.getFoto());
            ImageIcon imgRedimensionada = new ImageIcon(img.getImage().getScaledInstance(194, 105, 1));
            jLabelFoto.setIcon(imgRedimensionada);
            DecimalFormat formato = new DecimalFormat("#.##");
            jLabelCalificacion.setText("Valoración: " + formato.format(inm.getCalificacion()) + " /5 ("+inm.getNumCalificaciones()+")");
            jLabelLocalidad.setText(inm.getDireccion().getLocalidad() + ", C/" + inm.getDireccion().getCalle());
            jLabelPrecio.setText(String.valueOf(inm.getPrecioNoche()) + " € / noche");
            jLabelTitulo.setText(inm.getTitulo());
            if (inm.getAnfitrion().isSuperAnfitrion()){
                jLabelSuperAnfitrion.setText("¡SUPERANFITRIÓN!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Búsqueda de inmueble", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showPanel(JPanel p) {
        p.setSize(1060, 460);
        p.setLocation(0, 0);
        panelAnterior.removeAll();
        panelAnterior.add(p, BorderLayout.CENTER);
        panelAnterior.revalidate();
        panelAnterior.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalleVer;
    private javax.swing.JLabel jLabelCalificacion;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelSuperAnfitrion;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
