/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Marcos Barroso
 */
public class VentanaAdministrador extends javax.swing.JFrame {
    private final JFrame principal;
    /**
     * Creates new form VentanaAdministrador
     * @param ventana
     */
    public VentanaAdministrador(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIzq = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jButtonReservas = new javax.swing.JButton();
        jButtonInmuebles = new javax.swing.JButton();
        jPanelDch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaBNB - Administrador");
        setLocation(new java.awt.Point(150, 100));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelIzq.setBackground(new java.awt.Color(255, 153, 0));

        jLabelLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\marco\\OneDrive\\Escritorio\\1º G.I.INFO\\Asignaturas\\2º CUATR\\PROGRAMACIÓN\\PL FINAL\\PL2_Barroso_Carmona_23_24\\imagenes\\logojava2.png")); // NOI18N

        jButtonClientes.setBackground(new java.awt.Color(255, 204, 0));
        jButtonClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonClientes.setText("Consultar clientes");
        jButtonClientes.setBorder(null);
        jButtonClientes.setBorderPainted(false);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonReservas.setBackground(new java.awt.Color(255, 204, 0));
        jButtonReservas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonReservas.setText("Consultar reservas");
        jButtonReservas.setBorder(null);
        jButtonReservas.setBorderPainted(false);
        jButtonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservasActionPerformed(evt);
            }
        });

        jButtonInmuebles.setBackground(new java.awt.Color(255, 204, 0));
        jButtonInmuebles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonInmuebles.setText("Consultar inmuebles");
        jButtonInmuebles.setBorder(null);
        jButtonInmuebles.setBorderPainted(false);
        jButtonInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInmueblesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIzqLayout = new javax.swing.GroupLayout(jPanelIzq);
        jPanelIzq.setLayout(jPanelIzqLayout);
        jPanelIzqLayout.setHorizontalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jButtonInmuebles, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanelIzqLayout.setVerticalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInmuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jPanelDch.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido/a, has iniciado sesión como administrador.");

        javax.swing.GroupLayout jPanelDchLayout = new javax.swing.GroupLayout(jPanelDch);
        jPanelDch.setLayout(jPanelDchLayout);
        jPanelDchLayout.setHorizontalGroup(
            jPanelDchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDchLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addGap(118, 118, 118))
        );
        jPanelDchLayout.setVerticalGroup(
            jPanelDchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDchLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        // TODO add your handling code here:
        jButtonClientes.setBackground(Color.WHITE);
        jButtonReservas.setBackground(Color.ORANGE);
        jButtonInmuebles.setBackground(Color.ORANGE);
        PanelClientes pc = new PanelClientes();
        showPanel(pc);
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservasActionPerformed
        // TODO add your handling code here:
        jButtonReservas.setBackground(Color.WHITE);
        jButtonInmuebles.setBackground(Color.ORANGE);
        jButtonClientes.setBackground(Color.ORANGE);
        PanelReservas pr = new PanelReservas();
        showPanel(pr);
    }//GEN-LAST:event_jButtonReservasActionPerformed

    private void jButtonInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInmueblesActionPerformed
        // TODO add your handling code here:
        jButtonInmuebles.setBackground(Color.WHITE);
        jButtonReservas.setBackground(Color.ORANGE);
        jButtonClientes.setBackground(Color.ORANGE);
        PanelInmuebles pi = new PanelInmuebles(this);
        showPanel(pi);
    }//GEN-LAST:event_jButtonInmueblesActionPerformed
    
    private void showPanel(JPanel p){
        p.setSize(1109, 460);
        p.setLocation(0,0);
        jPanelContenido.removeAll();
        jPanelContenido.add(p,BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonInmuebles;
    private javax.swing.JButton jButtonReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelDch;
    private javax.swing.JPanel jPanelIzq;
    // End of variables declaration//GEN-END:variables
}
