/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import poo.clases.Particular;

/**
 *
 * @author Marcos Barroso
 */
public class VentanaParticular extends javax.swing.JFrame {
    
    private final JFrame principal;
    private final Particular particular;
    
    /**
     * Creates new form ParticularVentana
     * @param ventana
     * @param particular
     */
    public VentanaParticular(JFrame ventana,Particular particular) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.particular=particular;
        this.setVisible(true);
        if (particular.getTarjeta().getFechaCaducidad().isBefore(LocalDate.now())){
            JOptionPane.showMessageDialog(this, "Su tarjeta de crédito está caducada. Debe cambiarla.", "Particular", JOptionPane.ERROR_MESSAGE);
            PanelModifDatosParticular p = new PanelModifDatosParticular(particular,this,principal);
            showPanel(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIzq = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonModifDatos = new javax.swing.JButton();
        jButtonConsultarReservas = new javax.swing.JButton();
        jLabelLogo1 = new javax.swing.JLabel();
        jPanelDch = new javax.swing.JPanel();
        jLabelMensaje = new javax.swing.JLabel();
        jPanelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaBNB - Particular");
        setLocation(new java.awt.Point(150, 80));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelIzq.setBackground(new java.awt.Color(255, 153, 0));

        jButtonBuscar.setBackground(new java.awt.Color(255, 204, 0));
        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonBuscar.setText("Buscar inmuebles");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonModifDatos.setBackground(new java.awt.Color(255, 204, 0));
        jButtonModifDatos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonModifDatos.setText("Modificar mis datos");
        jButtonModifDatos.setBorder(null);
        jButtonModifDatos.setBorderPainted(false);
        jButtonModifDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifDatosActionPerformed(evt);
            }
        });

        jButtonConsultarReservas.setBackground(new java.awt.Color(255, 204, 0));
        jButtonConsultarReservas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonConsultarReservas.setText("Consultar reservas");
        jButtonConsultarReservas.setBorder(null);
        jButtonConsultarReservas.setBorderPainted(false);
        jButtonConsultarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarReservasActionPerformed(evt);
            }
        });

        jLabelLogo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\marco\\OneDrive\\Escritorio\\1º G.I.INFO\\Asignaturas\\2º CUATR\\PROGRAMACIÓN\\PL FINAL\\PL2_Barroso_Carmona_23_24\\imagenes\\logojava2.png")); // NOI18N

        javax.swing.GroupLayout jPanelIzqLayout = new javax.swing.GroupLayout(jPanelIzq);
        jPanelIzq.setLayout(jPanelIzqLayout);
        jPanelIzqLayout.setHorizontalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzqLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jButtonConsultarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonModifDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelIzqLayout.setVerticalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModifDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jPanelDch.setBackground(new java.awt.Color(255, 204, 153));

        jLabelMensaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMensaje.setText("Bienvenido/a [nombre], has iniciado sesión como particular.");

        javax.swing.GroupLayout jPanelDchLayout = new javax.swing.GroupLayout(jPanelDch);
        jPanelDch.setLayout(jPanelDchLayout);
        jPanelDchLayout.setHorizontalGroup(
            jPanelDchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDchLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
        );
        jPanelDchLayout.setVerticalGroup(
            jPanelDchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDchLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelMensaje)
                .addGap(30, 30, 30))
        );

        jPanelContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        jButtonBuscar.setBackground(Color.WHITE);
        jButtonConsultarReservas.setBackground(Color.ORANGE);
        jButtonModifDatos.setBackground(Color.ORANGE);
        PanelBuscarInm p = new PanelBuscarInm(this,particular);
        showPanel(p);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonConsultarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarReservasActionPerformed
        jButtonBuscar.setBackground(Color.ORANGE);
        jButtonConsultarReservas.setBackground(Color.WHITE);
        jButtonModifDatos.setBackground(Color.ORANGE);
        PanelReservasPar p = new PanelReservasPar(this,particular);
        showPanel(p);
    }//GEN-LAST:event_jButtonConsultarReservasActionPerformed

    private void jButtonModifDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifDatosActionPerformed
        jButtonBuscar.setBackground(Color.ORANGE);
        jButtonConsultarReservas.setBackground(Color.ORANGE);
        jButtonModifDatos.setBackground(Color.WHITE);
        PanelModifDatosParticular p = new PanelModifDatosParticular(particular,this,principal);
        showPanel(p);
    }//GEN-LAST:event_jButtonModifDatosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabelMensaje.setText("Bienvenido/a "+particular.getNombre().split(" ")[0]+", has iniciado sesión como particular.");
    }//GEN-LAST:event_formWindowOpened

    private void showPanel(JPanel p){
        p.setSize(1060, 550);
        p.setLocation(0,0);
        jPanelContenido.removeAll();
        jPanelContenido.add(p,BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonConsultarReservas;
    private javax.swing.JButton jButtonModifDatos;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelDch;
    private javax.swing.JPanel jPanelIzq;
    // End of variables declaration//GEN-END:variables
}
