/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import poo.clases.Anfitrion;

/**
 *
 * @author Marcos Barroso
 */
public class VentanaAnfitrion extends javax.swing.JFrame {
    private final JFrame principal;
    private final Anfitrion anfitrion;
    /**
     * Creates new form VentanaAnfitrion
     * @param ventana
     * @param a
     */
    public VentanaAnfitrion(JFrame ventana,Anfitrion a) {
        initComponents();
        this.anfitrion=a;
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIzq = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonConsultarInmueble = new javax.swing.JButton();
        jButtonAddInmueble = new javax.swing.JButton();
        jButtonConsultarReservas = new javax.swing.JButton();
        jButtonModifDatos = new javax.swing.JButton();
        jLabelLogo1 = new javax.swing.JLabel();
        jPanelDch = new javax.swing.JPanel();
        jLabelMensaje = new javax.swing.JLabel();
        jPanelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaBNB - Anfitrion");
        setLocation(new java.awt.Point(150, 100));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelIzq.setBackground(new java.awt.Color(255, 153, 0));

        jButtonConsultarInmueble.setBackground(new java.awt.Color(255, 204, 0));
        jButtonConsultarInmueble.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonConsultarInmueble.setText("Consultar inmuebles");
        jButtonConsultarInmueble.setBorder(null);
        jButtonConsultarInmueble.setBorderPainted(false);
        jButtonConsultarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarInmuebleActionPerformed(evt);
            }
        });

        jButtonAddInmueble.setBackground(new java.awt.Color(255, 204, 0));
        jButtonAddInmueble.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonAddInmueble.setText("Crear inmueble");
        jButtonAddInmueble.setBorder(null);
        jButtonAddInmueble.setBorderPainted(false);
        jButtonAddInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddInmuebleActionPerformed(evt);
            }
        });

        jButtonConsultarReservas.setBackground(new java.awt.Color(255, 204, 0));
        jButtonConsultarReservas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonConsultarReservas.setText("Consultar reservas");
        jButtonConsultarReservas.setBorder(null);
        jButtonConsultarReservas.setBorderPainted(false);
        jButtonConsultarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarReservasActionPerformed(evt);
            }
        });

        jButtonModifDatos.setBackground(new java.awt.Color(255, 204, 0));
        jButtonModifDatos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonModifDatos.setText("Modificar mis datos");
        jButtonModifDatos.setBorder(null);
        jButtonModifDatos.setBorderPainted(false);
        jButtonModifDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifDatosActionPerformed(evt);
            }
        });

        jLabelLogo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\marco\\OneDrive\\Escritorio\\1º G.I.INFO\\Asignaturas\\2º CUATR\\PROGRAMACIÓN\\PL FINAL\\PL2_Barroso_Carmona_23_24\\imagenes\\logojava2.png")); // NOI18N

        javax.swing.GroupLayout jPanelIzqLayout = new javax.swing.GroupLayout(jPanelIzq);
        jPanelIzq.setLayout(jPanelIzqLayout);
        jPanelIzqLayout.setHorizontalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonConsultarInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonConsultarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonModifDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelIzqLayout.createSequentialGroup()
                .addComponent(jLabelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jButtonAddInmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelIzqLayout.setVerticalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAddInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModifDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanelDch.setBackground(new java.awt.Color(255, 204, 153));

        jLabelMensaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMensaje.setText("Bienvenido/a [nombre], has iniciado sesión como anfitrión.");

        javax.swing.GroupLayout jPanelDchLayout = new javax.swing.GroupLayout(jPanelDch);
        jPanelDch.setLayout(jPanelDchLayout);
        jPanelDchLayout.setHorizontalGroup(
            jPanelDchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDchLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                .addGap(118, 118, 118))
        );
        jPanelDchLayout.setVerticalGroup(
            jPanelDchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDchLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelMensaje)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonConsultarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarInmuebleActionPerformed
        jButtonConsultarInmueble.setBackground(Color.WHITE);
        jButtonConsultarReservas.setBackground(Color.ORANGE);
        jButtonModifDatos.setBackground(Color.ORANGE);
        jButtonAddInmueble.setBackground(Color.ORANGE);
        PanelInmueblesAnf p = new PanelInmueblesAnf(anfitrion,this);
        showPanel(p);
    }//GEN-LAST:event_jButtonConsultarInmuebleActionPerformed

    private void jButtonAddInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddInmuebleActionPerformed
        jButtonConsultarInmueble.setBackground(Color.ORANGE);
        jButtonConsultarReservas.setBackground(Color.ORANGE);
        jButtonModifDatos.setBackground(Color.ORANGE);
        jButtonAddInmueble.setBackground(Color.WHITE);
        PanelCrearInmueble p = new PanelCrearInmueble(anfitrion);
        showPanel(p);
    }//GEN-LAST:event_jButtonAddInmuebleActionPerformed

    private void jButtonConsultarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarReservasActionPerformed
        jButtonConsultarInmueble.setBackground(Color.ORANGE);
        jButtonConsultarReservas.setBackground(Color.WHITE);
        jButtonModifDatos.setBackground(Color.ORANGE);
        jButtonAddInmueble.setBackground(Color.ORANGE);
        PanelReservasAnf p = new PanelReservasAnf(anfitrion);
        showPanel(p);
    }//GEN-LAST:event_jButtonConsultarReservasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabelMensaje.setText("Bienvenido/a "+anfitrion.getNombre().split(" ")[0]+", has iniciado sesión como anfitrión.");
    }//GEN-LAST:event_formWindowOpened

    private void jButtonModifDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifDatosActionPerformed
        jButtonConsultarInmueble.setBackground(Color.ORANGE);
        jButtonConsultarReservas.setBackground(Color.ORANGE);
        jButtonModifDatos.setBackground(Color.WHITE);
        jButtonAddInmueble.setBackground(Color.ORANGE);
        PanelModifDatosAnfitrion p = new PanelModifDatosAnfitrion(anfitrion,this,principal);
        showPanel(p);
    }//GEN-LAST:event_jButtonModifDatosActionPerformed
    private void showPanel(JPanel p){
        p.setSize(1060, 460);
        p.setLocation(0,0);
        jPanelContenido.removeAll();
        jPanelContenido.add(p,BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddInmueble;
    private javax.swing.JButton jButtonConsultarInmueble;
    private javax.swing.JButton jButtonConsultarReservas;
    private javax.swing.JButton jButtonModifDatos;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelDch;
    private javax.swing.JPanel jPanelIzq;
    // End of variables declaration//GEN-END:variables
}
